AllCards = [
	{
		"@ace": "",
		"image": "assets/1-1.jpg",
		"value": "1",
		"suit1": "A",
		"suit1b": "a",
		"suit1[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"description": "The suit of Moons represents wisdom, especially divine wisdom. It is associated with mysteries, things hidden, and the inescapable truth that the world outstrips our knowledge. "
	},
	{
		"@ace": "",
		"image": "assets/1-2.jpg",
		"value": "1",
		"suit1": "B",
		"suit1b": "b",
		"suit1[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"description": "The suit of Suns represents power, perhaps divine power. It is associated with decisive action and clarity of purpose. "
	},
	{
		"@ace": "",
		"image": "assets/1-3.jpg",
		"value": "1",
		"suit1": "C",
		"suit1b": "c",
		"suit1[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"description": "Water is the hand of the earth, which presses on all things. The suit of Waves represents nature as an active force. It is associated with weather, natural cycles, and the passage of time. "
	},
	{
		"@ace": "",
		"image": "assets/1-4.jpg",
		"value": "1",
		"suit1": "D",
		"suit1b": "d",
		"suit1[style:fill]": "#000000",
		"suit1b[style:fill]": "#b6804e",
		"description": "Wood is the gift of the earth, from which things begin and in which things end. The suit of Wood represents nature as matter. Also known as the Leaves or the Trees, the suit is associated with raw materials and food products. "
	},
	{
		"@ace": "",
		"image": "assets/1-5.jpg",
		"value": "1",
		"suit1": "E",
		"suit1b": "e",
		"suit1[style:fill]": "#000000",
		"suit1b[style:fill]": "#51bf49",
		"description": "Unnatural and at home underground, the Wyrm brings violence and feeds on dreams. This is the most negative of the suits. Most broadly, it represents things that are innappropriate or disruptive. "
	},
	{
		"@ace": "",
		"image": "assets/1-6.jpg",
		"value": "1",
		"suit1": "F",
		"suit1b": "f",
		"suit1[style:fill]": "#000000",
		"suit1b[style:fill]": "#ebf04b",
		"description": "The suit of Knots represents craft, skill, and refinement. It is associated with worked goods, commerce, and money. "
	},
	{
		"@": "border",
		"image": "assets/2-1.jpg",
		"title": "the AUTHOR",
		"value": "2",
		"suit1": "A",
		"suit2": "F",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "The Author is an artisan, like the Painter and the Bard. The important difference between them is their relation to the facts that they present. As a Moon card, the Author faces mysteries. So the Author is a character of investigation, enquiry, and at most partial answers. "
	},
	{
		"@": "border",
		"image": "assets/2-2.jpg",
		"title": "|^the ORIGIN",
		"value": "2",
		"suit1": "C",
		"suit2": "D",
		"suit3": "",
		"suit1b": "c",
		"suit2b": "d",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"suit2b[style:fill]": "#b6804e",
		"suit3b[style:fill]": "",
		"description": "Morning light shines through clear water. The Origin can appear as either a location or an event. As an event, it is morning light. As a location, it is a living spring. "
	},
	{
		"@": "border",
		"image": "assets/2-3.jpg",
		"title": "|the DESERT",
		"value": "2",
		"suit1": "B",
		"suit2": "E",
		"suit3": "",
		"suit1b": "b",
		"suit2b": "e",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"suit2b[style:fill]": "#51bf49",
		"suit3b[style:fill]": "",
		"description": "Barren and without life, the Desert offers a certain grim clarity. Yet clarity might itself be a mirage. "
	},
	{
		"@": "border",
		"image": "assets/3-1.jpg",
		"title": "the SAVAGE",
		"value": "3",
		"suit1": "D",
		"suit2": "E",
		"suit3": "",
		"suit1b": "d",
		"suit2b": "e",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#b6804e",
		"suit2b[style:fill]": "#51bf49",
		"suit3b[style:fill]": "",
		"description": "Even if the Savage presents a pleasant face, the wild lurks in his heart. "
	},
	{
		"@": "border",
		"image": "assets/3-2.jpg",
		"title": "the PAINTER",
		"value": "3",
		"suit1": "B",
		"suit2": "F",
		"suit3": "",
		"suit1b": "b",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "The Painter is a figure of revelation. The Painter sees through posturing and portrays things as they need to be portrayed."
	},
	{
		"@": "border",
		"image": "assets/3-3.jpg",
		"title": "^the JOURNEY",
		"value": "3",
		"suit1": "A",
		"suit2": "C",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "c",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#8cb8e6",
		"suit3b[style:fill]": "",
		"description": "The Journey is in between. It is its own story, written between departure and arrival. "
	},
	{
		"@": "border",
		"image": "assets/4-1.jpg",
		"title": "^the BATTLE",
		"value": "4",
		"suit1": "E",
		"suit2": "F",
		"suit3": "",
		"suit1b": "e",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#51bf49",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "Struggle with forces that are half in shadow. It is not always obvious what those forces are until they have done their worst."
	},
	{
		"@": "border",
		"image": "assets/4-2.jpg",
		"title": "|the MOUNTAIN",
		"value": "4",
		"suit1": "A",
		"suit2": "B",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "b",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#f68312",
		"suit3b[style:fill]": "",
		"description": "A quest leads to the peak. Especially if the Mountain appears in a spread with the Journey, to the peak may be more important than at the peak. "
	},
	{
		"@": "border",
		"image": "assets/4-3.jpg",
		"title": "the SAILOR",
		"value": "4",
		"suit1": "C",
		"suit2": "D",
		"suit3": "",
		"suit1b": "c",
		"suit2b": "d",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"suit2b[style:fill]": "#b6804e",
		"suit3b[style:fill]": "",
		"description": "On the wall of the sailor's house: He is not at home at home. The Sailor is a traveller by nature, uneasy when not underway. "
	},
	{
		"@": "border",
		"image": "assets/5-1.jpg",
		"title": "^the DISCOVERY",
		"value": "5",
		"suit1": "B",
		"suit2": "C",
		"suit3": "",
		"suit1b": "b",
		"suit2b": "c",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"suit2b[style:fill]": "#8cb8e6",
		"suit3b[style:fill]": "",
		"description": "Something buried or lost is found. The Discovery may be the end of a quest or as surprising as a sudden storm."
	},
	{
		"@": "border",
		"image": "assets/5-2.jpg",
		"title": "the SOLDIER",
		"value": "5",
		"suit1": "E",
		"suit2": "F",
		"suit3": "",
		"suit1b": "e",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#51bf49",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "Like words to the Author or money to the Merchant, war is craft to the Soldier. Although the conflict might not be a literal war, the Soldier lives for it. The soldier's craft is wrought in stillness and motion. Of all the personalities, the Soldier shows the least difference between its two faces. "
	},
	{
		"@": "border",
		"image": "assets/5-3.jpg",
		"title": "|the FOREST",
		"value": "5",
		"suit1": "A",
		"suit2": "D",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "d",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#b6804e",
		"suit3b[style:fill]": "",
		"description": "The Forest is usually a literal card representing a forest or wooded place. In a crowded city, however, sometimes even a single tree can be a forest. "
	},
	{
		"@": "border",
		"image": "assets/6-1.jpg",
		"title": "|^the MARKET",
		"value": "6",
		"suit1": "D",
		"suit2": "F",
		"suit3": "",
		"suit1b": "d",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#b6804e",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "The Market can appear as either a location or an event. As a location, the Market is a place of trade. As an event, the Market is commerce. Unlike the Pact, it does not suggest a great confluence; an exchange, and the matter is resolved. "
	},
	{
		"@": "border",
		"image": "assets/6-2.jpg",
		"title": "the PENITENT",
		"value": "6",
		"suit1": "B",
		"suit2": "E",
		"suit3": "",
		"suit1b": "b",
		"suit2b": "e",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"suit2b[style:fill]": "#51bf49",
		"suit3b[style:fill]": "",
		"description": "A higher calling hides a darker past. Redemption is never entirely complete for the Penitent."
	},
	{
		"@": "border",
		"image": "assets/6-3.jpg",
		"title": "the LUNATIC",
		"value": "6",
		"suit1": "A",
		"suit2": "C",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "c",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#8cb8e6",
		"suit3b[style:fill]": "",
		"description": "The Lunatic sees things that no one else sees. Perhaps these are deeper truths, perhaps they are delusions. Watch the great tumult around her. "
	},
	{
		"@": "border",
		"image": "assets/7-1.jpg",
		"title": "^the CHANCE MEETING",
		"value": "7",
		"suit1": "A",
		"suit2": "D",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "d",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#b6804e",
		"suit3b[style:fill]": "",
		"description": "Two stories half-written find themselves writing one another. The Chance Meeting is a card of possibilities."
	},
	{
		"@": "border",
		"image": "assets/7-2.jpg",
		"title": "|the CASTLE",
		"value": "7",
		"suit1": "B",
		"suit2": "F",
		"suit3": "",
		"suit1b": "b",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "The Castle is a community. It is a place of civility or power, but only rarely of both. "
	},
	{
		"@": "border",
		"image": "assets/7-3.jpg",
		"title": "|the CAVE",
		"value": "7",
		"suit1": "C",
		"suit2": "E",
		"suit3": "",
		"suit1b": "c",
		"suit2b": "e",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"suit2b[style:fill]": "#51bf49",
		"suit3b[style:fill]": "",
		"description": "It is home to grim things and a place of challenges. Things that fall below the surface may be found in the Cave, even if they were long thought lost or destroyed. To enter and return from it once should be enough. "
	},
	{
		"@": "border",
		"image": "assets/8-1.jpg",
		"title": "^the BETRAYAL",
		"value": "8",
		"suit1": "E",
		"suit2": "F",
		"suit3": "",
		"suit1b": "e",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#51bf49",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "Even a soft hand can wield a sharp knife. This is a time to be wary."
	},
	{
		"@": "border",
		"image": "assets/8-2.jpg",
		"title": "the DIPLOMAT",
		"value": "8",
		"suit1": "A",
		"suit2": "B",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "b",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#f68312",
		"suit3b[style:fill]": "",
		"description": "The Diplomat mediates between opposites: darkness and light, patience and action, the one and the many. "
	},
	{
		"@": "border",
		"image": "assets/8-3.jpg",
		"title": "|the MILL",
		"value": "8",
		"suit1": "C",
		"suit2": "D",
		"suit3": "",
		"suit1b": "c",
		"suit2b": "d",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"suit2b[style:fill]": "#b6804e",
		"suit3b[style:fill]": "",
		"description": "The Mill is a place of craft and production. The tuneless song of the miller is lost in the roar of the water and the ceaseless turning of the wheel."
	},
	{
		"@": "border",
		"image": "assets/9-1.jpg",
		"title": "^the PACT",
		"value": "9",
		"suit1": "A",
		"suit2": "B",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "b",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "#f68312",
		"suit3b[style:fill]": "",
		"description": "When the two kings agree, the stones themselves agree. Even a Pact between just two parties has ramifications for the community and the broader world. "
	},
	{
		"@": "border",
		"image": "assets/9-2.jpg",
		"title": "the MERCHANT",
		"value": "9",
		"suit1": "D",
		"suit2": "F",
		"suit3": "",
		"suit1b": "d",
		"suit2b": "f",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#b6804e",
		"suit2b[style:fill]": "#ebf04b",
		"suit3b[style:fill]": "",
		"description": "For the Merchant, wealth is its own end. The Merchant amasses riches, but worries all the while about losing them. "
	},
	{
		"@": "nborder",
		"image": "assets/9-3.jpg",
		"title": "|the DARKNESS",
		"value": "9",
		"suit1": "C",
		"suit2": "E",
		"suit3": "",
		"suit1b": "c",
		"suit2b": "e",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"suit2b[style:fill]": "#51bf49",
		"suit3b[style:fill]": "",
		"description": "The Darkness can settle on familiar places and hides all manner of things. Although one may hide there or seek for what is lost there, it is best not to tarry there too long. Unlike the Cave, it is sometimes best to illuminate and dispel the Darkness rather than to flee from it. "
	},
	{
		"@": "border",
		"image": "assets/10-1.jpg",
		"title": "the BARD",
		"value": "*",
		"suit1": "B",
		"suit2": "",
		"suit3": "",
		"suit1b": "b",
		"suit2b": "",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#f68312",
		"suit2b[style:fill]": "",
		"suit3b[style:fill]": "",
		"description": "The Bard speaks and people listen. Whereas the Painter can paint the world as it is, things become the way the Bard says they ought to be. "
	},
	{
		"@": "border",
		"image": "assets/10-2.jpg",
		"title": "the HUNTRESS",
		"value": "*",
		"suit1": "A",
		"suit2": "",
		"suit3": "",
		"suit1b": "a",
		"suit2b": "",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#c8c7c8",
		"suit2b[style:fill]": "",
		"suit3b[style:fill]": "",
		"description": "The Huntress finds her mark, like an arrow loosed from a bow. She is a seeker, even if she is unsure what she is seeking, and she is on a quest even in her idle moments. The Huntress stands in the natural world, like a tree in the forest. In some ways, she acts just like an animal; she moves without reflection, in accord with her nature. "
	},
	{
		"@": "border",
		"image": "assets/10-3.jpg",
		"title": "|the SEA",
		"value": "*",
		"suit1": "C",
		"suit2": "",
		"suit3": "",
		"suit1b": "c",
		"suit2b": "",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#8cb8e6",
		"suit2b[style:fill]": "",
		"suit3b[style:fill]": "",
		"description": "The Sea is often literally some large body of water. As a symbol, it is the source of storms. "
	},
	{
		"@": "border",
		"image": "assets/10-4.jpg",
		"title": "|^the END",
		"value": "*",
		"suit1": "D",
		"suit2": "",
		"suit3": "",
		"suit1b": "d",
		"suit2b": "",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#b6804e",
		"suit2b[style:fill]": "",
		"suit3b[style:fill]": "",
		"description": "The End can appear as either a location or an event. As an event, the End is the conclusion of the cycle before the beginnings of the next moment are even buds on the branches. As a location, the End is a terminus at the border of known lands with nothing on the other side. "
	},
	{
		"@": "border",
		"image": "assets/10-5.jpg",
		"title": "^the CALAMITY",
		"value": "*",
		"suit1": "E",
		"suit2": "",
		"suit3": "",
		"suit1b": "e",
		"suit2b": "",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#51bf49",
		"suit2b[style:fill]": "",
		"suit3b[style:fill]": "",
		"description": "Death so sudden that there is no time to bury the dead. Although it can be mitigated by other cards in the spread, the Calamity is always a bad thing. "
	},
	{
		"@": "border",
		"image": "assets/10-6.jpg",
		"title": "^the WINDFALL",
		"value": "*",
		"suit1": "F",
		"suit2": "",
		"suit3": "",
		"suit1b": "f",
		"suit2b": "",
		"suit3b": "",
		"suit1[style:fill]": "#000000",
		"suit2[style:fill]": "#000000",
		"suit3[style:fill]": "#000000",
		"suit1b[style:fill]": "#ebf04b",
		"suit2b[style:fill]": "",
		"suit3b[style:fill]": "",
		"description": "One might have quested for it, if one had known, but it comes unannounced. The Windfall on its own is always a positive card. If there is any cost or caveat, it must come from somewhere else. "
	}
]
